# 脚本用户相关信息
# 用来填在某些没啥用的地方（比如纷玩岛的电子票姓名那一栏)
ghost:
  ghost_name: Tachikoma
  ghost_mobile: 00000000000

# 金主相关信息
# 多个请保持对应顺序
# 用不到的信息可以不填（比如电话，如果是非必填可以不改，留着以防某个APP是必须项）
buyer:
  buyer_name:
    - 王潮暾
    - 刘柯芳
  buyer_id:
    - 150627200104050611
    - 152827200107110029
  buyer_mobile:
    - 00000000000
    - 00000000000

# 票价信息
ticket:
  # 目标票价（整数，必填）
  target_price: 580

  # 目标票价的档位
  # 说明：大麦、纷玩岛换刷票流程后，不再需要填写；猫眼需要填写。
  #   纷玩岛：内场1155（参考页面填写，不用全写，能唯一标志出来即可）
  #   大麦：1（数字序号，从上到下、从左到右、从0开始数）
  #   猫眼：¥580（参考页面填写，不用全写，能唯一标志出来即可）
  target_tier: 内场580

  # 场次
  # 说明：大麦、纷玩岛暂时不用填；猫眼以后再说。填写规则同上，注意两个日期是字符串。
  #   纷玩岛："2024-07-31"
  #   大麦：0
  #   猫眼："2024-10-19"
  ticket_tier: "2024-09-29"

  # 刷回流用信息
  # 说明：大麦、纷玩岛暂时不用填；猫眼以后再说。填写规则同上。
  #   纷玩岛：看台955（填写另一个票价档位）
  #   大麦：2（填写另一个场次档位）←老要求备份，大麦暂时不用填写这个（使用退出重进来刷票）
  #   猫眼：内场¥1280（填写另一个票价档位）←老要求备份，猫眼暂时不用填写这个（使用点击目标场次和票价来刷票）
  coop_tier: 看台880

# 抢票时间设置
scheduler:
  # 设定时间，格式：2020-02-24 10:00:00.1000，可以适当提前100-200ms（注意是字符串）
  trigger: "2024-07-26 14:59:59.500"