# 脚本用户相关信息
# 用来填在某些没啥用的地方（比如纷玩岛的电子票姓名那一栏)
ghost:
  ghost_name: Tachikoma

# 金主相关信息
# 有多个请保持对应顺序
buyer:
  buyer_name:
    - 王潮暾
    - 刘柯芳
  buyer_id:
    - 150627200104050611
    - 152827200107110029

# 票价信息
ticket:
  # 目标票价（整数，必填）
  ticket_price: 580

  # 目标票价的档位
  # 说明：目前大麦、猫眼、纷玩岛都不需要填写。暂时保留以防不测。
  #   纷玩岛：内场1155（参考页面填写，不用全写，能唯一标志出来即可）
  #   大麦：1（数字序号，从上到下、从左到右、从0开始数）
  #   猫眼：¥580（参考页面填写，不用全写，能唯一标志出来即可）
  ticket_tier: 内场580

  # 场次信息
  # 说明：目前大麦、猫眼、纷玩岛都不需要填写。暂时保留以防不测。
  #   纷玩岛："2024-07-31"
  #   大麦：0
  #   猫眼："2024-10-19"
  ticket_date: "2024-09-29"

# 抢票时间设置
scheduler:
  # 设定时间，格式：2020-02-24 10:00:00.1000，可以适当提前100-200ms（注意是字符串）
  trigger: "2024-07-26 14:59:59.500"