# 脚本用户相关信息，用来填在某些没啥用的地方（比如纷玩岛的电子票那一栏)
ghost:
  ghost_name: Tachikoma
  ghost_mobile: 00000000000

# 金主相关信息
# 多个请按顺序填写
# 用不到的信息不填（比如电话，如果是非必填可以不改）
buyer:
  buyer_name:
    - 朱建飞
  buyer_id:
    - 152629198910140595
  buyer_mobile:
    - 00000000000

# 纷玩岛购票信息
ticket_livelab:
  # 目标票价
  target_price: 955
  # 目标票价的档位，参考页面情况填写类似：内场1155（不用全写，能唯一标志出来即可）
  target_tier: 看台955
  # 另一个票价（用来刷回流，不会买），规则同上
  coop_tier: 看台355
  # 场次的档位，规则同上（注意是字符串）
  ticket_tier: "2024-07-31"

# 大麦购票信息
ticket_damai:
  # 目标票价
  target_price: 699
  # 目标票价的档位：从上到下、从左到右、从0开始数
  target_tier: 2
  # 场次的档位，规则同上
  ticket_tier: 0
  # 另一个场次（用来刷回流，不会买），规则同上
  coop_tier: 1

# 猫眼购票信息
ticket_maoyan:
  # 目标票价
  target_price: 580
  # 目标票价的档位，参考页面情况填写类似：内场1155（不用全写，能唯一标志出来即可）
  target_tier: 看台¥580
  # 另一个票价（用来刷回流，不会买），规则同上
  coop_tier: 内场¥1280
  # 场次的档位，规则同上（注意是字符串）
  ticket_tier: "2024-10-19"

# 抢票时间设置
scheduler:
  # 设定时间，格式：2020-02-24 10:00:00.1000，可以适当提前100-200ms（注意是字符串）
  trigger: "2024-07-21 15:57:59.800"